---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: windows-2012r2
    driver:
      box: 'jonathanporta/windows-2012r2-standard'
      communicator: 'winrm'

suites:
  - name: default
    run_list:
      - recipe[steamcmd_test]
    attributes:
